In [116]:
import torch

print(torch.__version__)

2.4.0+cpu


Tensor Types and Basic Functions

Pytorch tensors created - "torch.tensor"

Scalar: Single number (quantity and value).
Vector: 1D array of values (has direction and magnitude).
Matrix: 2D array of values (rows and columns).
Tensor: Multi-dimensional array of values (more than 2 dimensions).

LT -> Skalaras: Vienas skaičius (kiekis ir reikšmė).
Vektorius: Vienmatė reikšmių seka (turi kryptį ir dydį).
Matricos: Dvimatė reikšmių lentelė (iš eilių ir stulpelių).
Tenzorius: Daugiamatė reikšmių lentelė (n > 2 dimensijos).

In [117]:
# Scalar
scalar = torch.tensor(8)
scalar

tensor(8)

In [118]:
# How many dimension scalar haves
scalar.ndim

0

In [119]:
# Checking the shape of scalar -> shows all lists and how many items is there in list, because scalar doesn't have list just one item, that's why it is empty
scalar.shape

torch.Size([])

In [120]:
scalar.size()

torch.Size([])

In [121]:
# Get tensor back as a standard Python number
scalar.item()

8

In [122]:
# Tensor data types
scalar.dtype

torch.int64

In [123]:
# Vector
vector = torch.tensor([1, 2, 3, 4, 5])
vector

tensor([1, 2, 3, 4, 5])

In [124]:
# How many dimension vector haves
vector.ndim

1

In [125]:
# Checking the shape of vector -> shows all lists and how many items is there in list
vector.shape

torch.Size([5])

In [126]:
vector.size()

torch.Size([5])

In [127]:
# Tensor data types
vector.dtype

torch.int64

In [128]:
# Get vector elements by index
vector[0]

tensor(1)

In [129]:
vector[0:2]

tensor([1, 2])

In [130]:
# Matrix
MATRIX = torch.tensor([[1, 2, 3, 4, 5], 
                       [1, 2, 3, 4, 5]])
MATRIX

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [131]:
# How many dimension matrix haves
MATRIX.ndim

2

In [132]:
# Checking the shape of vector -> shows all lists and how many items is there in list
MATRIX.shape

torch.Size([2, 5])

In [133]:
MATRIX.size()

torch.Size([2, 5])

In [134]:
# Tensor data types
MATRIX.dtype

torch.int64

In [135]:
# Get matrix elements by index
MATRIX[0]

tensor([1, 2, 3, 4, 5])

In [136]:
MATRIX[0][1]

tensor(2)

In [137]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]], [[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]])
TENSOR

tensor([[[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]],

        [[1, 2, 3, 4, 5],
         [1, 2, 3, 4, 5]]])

In [138]:
# How many dimension tensor haves
TENSOR.ndim

3

In [139]:
# Checking the shape of tensor -> shows all lists and how many items is there in list
TENSOR.shape

torch.Size([2, 2, 5])

In [140]:
TENSOR.size()

torch.Size([2, 2, 5])

In [141]:
# Tensor data types
TENSOR.dtype

torch.int64

In [142]:
# Get tensor elements by index
TENSOR[0]

tensor([[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]])

In [143]:
TENSOR[0][0]

tensor([1, 2, 3, 4, 5])

In [144]:
TENSOR[0][1][0]

tensor(1)