In [40]:
import torch

Random Tensors

Random tensors aid in model initialization, data augmentation, and training efficiency. The model learns patterns from diverse samples during training.

LT -> Atsitiktiniai tenzoriai padeda modelio inicializavimui, duomenų praplėtimui ir mokymo efektyvumui. Modelis mokosi atpažinti raštus iš įvairių pavyzdžių mokymo metu.

Example: Training a robot to recognize chickens involves showing it varied images of chickens and other animals. Random tensors represent these varied images, helping the model learn and improve its recognition skills.

LT -> Pavyzdys: Mokant robotą atpažinti vištas, jam rodomos įvairios vištų ir kitų gyvūnų nuotraukos. Atsitiktiniai tenzoriai atspindi šias įvairias nuotraukas, padėdami modeliui tobulinti atpažinimo įgūdžius.

In [41]:
# Random tensor
RANDOM_TENSOR = torch.rand(2, 2, 2)
RANDOM_TENSOR

tensor([[[0.0204, 0.6226],
         [0.0089, 0.6280]],

        [[0.4461, 0.2286],
         [0.0664, 0.6952]]])

In [42]:
# Random tensor dimensions
RANDOM_TENSOR.ndim

3

In [43]:
# Random tensor with similar shape to an image tensor
# PyTorch uses the channel-first format ((C, H, W))
# PyTorch tensor for image -> size=(colour channels (R, G, B), height, width)
RANDOM_IMG_TENSOR = torch.rand(size=(3, 128, 128))  # colour channels (R, G, B), height, width
RANDOM_IMG_TENSOR

tensor([[[0.8097, 0.3145, 0.5737,  ..., 0.2311, 0.5125, 0.8097],
         [0.6846, 0.9890, 0.8954,  ..., 0.5940, 0.5929, 0.9049],
         [0.4109, 0.3563, 0.1404,  ..., 0.4762, 0.7305, 0.7622],
         ...,
         [0.4371, 0.9126, 0.4181,  ..., 0.6800, 0.7452, 0.7573],
         [0.6488, 0.8657, 0.2467,  ..., 0.9875, 0.6259, 0.6983],
         [0.8706, 0.5160, 0.8822,  ..., 0.4299, 0.8750, 0.9695]],

        [[0.7610, 0.8295, 0.0884,  ..., 0.2374, 0.7499, 0.9922],
         [0.5217, 0.5753, 0.8724,  ..., 0.6318, 0.6163, 0.3583],
         [0.1771, 0.3003, 0.7198,  ..., 0.4518, 0.9411, 0.9114],
         ...,
         [0.4660, 0.1060, 0.3641,  ..., 0.8032, 0.8722, 0.4924],
         [0.0083, 0.0124, 0.2258,  ..., 0.1334, 0.8430, 0.6218],
         [0.2683, 0.7962, 0.2847,  ..., 0.0961, 0.2561, 0.3902]],

        [[0.8870, 0.0786, 0.2439,  ..., 0.2012, 0.3275, 0.9437],
         [0.6591, 0.7582, 0.9895,  ..., 0.1045, 0.9343, 0.2067],
         [0.7313, 0.6296, 0.0034,  ..., 0.4999, 0.5013, 0.

In [44]:
RANDOM_IMG_TENSOR.shape, RANDOM_IMG_TENSOR.ndim

(torch.Size([3, 128, 128]), 3)

In [45]:
# Create tensor of 0
ZERO = torch.zeros(size=(2, 2, 2))
ZERO

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [46]:
# Create tensor of 1
ONES = torch.ones(size=(2, 2, 2))
ONES

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [47]:
# Tensor data types
RANDOM_TENSOR.dtype, RANDOM_IMG_TENSOR.dtype, ZERO.dtype, ONES.dtype

(torch.float32, torch.float32, torch.float32, torch.float32)