In [9]:
import torch

torch.arange: Creates a tensor with a sequence of numbers from start to end (exclusive) with a specified step.

torch.zeros_like: Creates a tensor of zeros with the same shape and dtype as the given tensor.

torch.ones_like: Creates a tensor of ones with the same shape and dtype as the given tensor.

In [10]:
# Create tensor in range(start, end, step)
in_range = torch.arange(1, 22, 2)
in_range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [11]:
in_range_2 = torch.arange(start=2, end=24, step=5)
in_range_2

tensor([ 2,  7, 12, 17, 22])

In [12]:
# Create tensor like (replicate tensor shape)
replicate_tensor_zeros = torch.zeros_like(input=in_range)
replicate_tensor_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
replicate_tensor_zeros = torch.ones_like(input=in_range)
replicate_tensor_zeros

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])