In [392]:
import torch

https://lt.wikipedia.org/wiki/Matrica_(matematika)

Addition: result = tensor1 + tensor2 or result = torch.add(tensor1, tensor2) or tensor1 + number

Subtraction: result = tensor1 - tensor2 or result = torch.sub(tensor1, tensor2) or tensor1 + number

Multiplication: result = tensor1 * tensor2 or result = torch.mul(tensor1, tensor2) or tensor1 * number <- Element by Element

Division: result = tensor1 / tensor2 or result = torch.div(tensor1, tensor2) or tensor1 / number <- Element by Element

Matrix Multiplication: result = torch.matmul(tensor1, tensor2) or using @ operator in Python 3.5+: result = tensor1 @ tensor2

Matrix Division: doesn't have.

In [393]:
first_tensor = torch.tensor([[1, 2], 
                             [3, 4]])
second_tensor = torch.tensor([[5, 6], 
                              [7, 8]])

In [394]:
# Subtraction
first_tensor - 10, torch.sub(first_tensor, 10)

(tensor([[-9, -8],
         [-7, -6]]),
 tensor([[-9, -8],
         [-7, -6]]))

In [395]:
first_tensor + second_tensor, torch.add(first_tensor, second_tensor)

(tensor([[ 6,  8],
         [10, 12]]),
 tensor([[ 6,  8],
         [10, 12]]))

In [396]:
# Addition
first_tensor + 10, torch.add(first_tensor, 10)

(tensor([[11, 12],
         [13, 14]]),
 tensor([[11, 12],
         [13, 14]]))

In [397]:
torch.add(first_tensor, second_tensor)

tensor([[ 6,  8],
        [10, 12]])

In [398]:
# Multiplication (Element by Element)
first_tensor * 10, torch.mul(first_tensor, 10)

(tensor([[10, 20],
         [30, 40]]),
 tensor([[10, 20],
         [30, 40]]))

In [399]:
torch.mul(first_tensor, second_tensor)

tensor([[ 5, 12],
        [21, 32]])

In [400]:
# Division (Element by Element)
first_tensor / 10, torch.div(first_tensor, 10)

(tensor([[0.1000, 0.2000],
         [0.3000, 0.4000]]),
 tensor([[0.1000, 0.2000],
         [0.3000, 0.4000]]))

In [401]:
torch.div(first_tensor, second_tensor)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Matrix multiplication sample

A = [3 1,
     2 1,
     1 0]
    
B = [1 0 2,
    -1 3 1]

C = A x B

(3×1)+(1×−1) = 3−1 = 2
(3×0)+(1×3) = 0+3 = 3
(3×2)+(1×1) = 6+1 = 7

(2×1)+(1×−1) = 2−1 = 1
(2×0)+(1×3) = 0+3 = 3
(2×2)+(1×1) = 4+1 = 5

(1×1)+(0×−1) = 1+0 = 1
(1×0)+(0×3) = 0+0 = 0
(1×2)+(0×1) = 2+0 = 2

C = [2 3 7,
     1 3 5,
     1 0 2]

In [402]:
# Matrix Multiplication
first_tensor @ second_tensor, torch.matmul(first_tensor, second_tensor)

(tensor([[19, 22],
         [43, 50]]),
 tensor([[19, 22],
         [43, 50]]))

In [403]:
# Can only multiply matrices that the number of columns in the first matrix must equal the number of rows in the second matrix
torch.rand(3, 2) @ torch.rand(2, 3)

tensor([[0.4452, 0.1523, 0.4762],
        [0.2576, 0.1179, 0.2752],
        [0.2902, 0.0251, 0.3114]])

In [404]:
torch.rand(3, 2) @ torch.rand(3, 2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [405]:
# To multiply tensors, if one tensor has a shape like (3, 3, 2), the other tensor must also have the same number of matrices in the first dimension. In this case, both tensors should have a shape of (3, X, Y) where X and Y can be different, but X must match the second-to-last dimension of the first tensor.
torch.rand(3, 3, 2) @ torch.rand(3, 2, 3)

tensor([[[0.2789, 0.5253, 0.5152],
         [0.2070, 0.3914, 0.4042],
         [0.0892, 0.1698, 0.1920]],

        [[1.2262, 0.8357, 0.5085],
         [1.1119, 0.8349, 0.6133],
         [0.8598, 0.6761, 0.5345]],

        [[0.1534, 0.9700, 0.4605],
         [0.1360, 0.4759, 0.3529],
         [0.1581, 0.8837, 0.4578]]])

In [406]:
torch.rand(3, 3, 2) @ torch.rand(4, 2, 3)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [407]:
# Fix shape error
# Switch axes or dimensions of tensor (transpose)
tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[5, 6], 
                         [7, 8], 
                         [9, 10]])

tensor_A, tensor_A.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

In [408]:
tensor_A.shape, tensor_A.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [409]:
# Change tensor_A shape "tensor_A.T"
torch.matmul(tensor_A.T, tensor_B), 

(tensor([[ 71,  80],
         [ 92, 104]]),)

In [410]:
# Didn't change tensor_A shape and got error
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)