In [373]:
import torch

https://lt.wikipedia.org/wiki/Matrica_(matematika)

Addition: result = tensor1 + tensor2 or result = torch.add(tensor1, tensor2) or tensor1 + number

Subtraction: result = tensor1 - tensor2 or result = torch.sub(tensor1, tensor2) or tensor1 + number

Multiplication: result = tensor1 * tensor2 or result = torch.mul(tensor1, tensor2) or tensor1 * number <- Element by Element

Division: result = tensor1 / tensor2 or result = torch.div(tensor1, tensor2) or tensor1 / number <- Element by Element

Matrix Multiplication: result = torch.matmul(tensor1, tensor2) or using @ operator in Python 3.5+: result = tensor1 @ tensor2

Matrix Division: doesn't have.

In [374]:
first_tensor = torch.tensor([[1, 2], 
                             [3, 4]])
second_tensor = torch.tensor([[5, 6], 
                              [7, 8]])

In [375]:
# Subtraction
first_tensor - 10, torch.sub(first_tensor, 10)

(tensor([[-9, -8],
         [-7, -6]]),
 tensor([[-9, -8],
         [-7, -6]]))

In [376]:
first_tensor + second_tensor, torch.add(first_tensor, second_tensor)

(tensor([[ 6,  8],
         [10, 12]]),
 tensor([[ 6,  8],
         [10, 12]]))

In [377]:
# Addition
first_tensor + 10, torch.add(first_tensor, 10)

(tensor([[11, 12],
         [13, 14]]),
 tensor([[11, 12],
         [13, 14]]))

In [378]:
torch.add(first_tensor, second_tensor)

tensor([[ 6,  8],
        [10, 12]])

In [379]:
# Multiplication (Element by Element)
first_tensor * 10, torch.mul(first_tensor, 10)

(tensor([[10, 20],
         [30, 40]]),
 tensor([[10, 20],
         [30, 40]]))

In [380]:
torch.mul(first_tensor, second_tensor)

tensor([[ 5, 12],
        [21, 32]])

In [381]:
# Division (Element by Element)
first_tensor / 10, torch.div(first_tensor, 10)

(tensor([[0.1000, 0.2000],
         [0.3000, 0.4000]]),
 tensor([[0.1000, 0.2000],
         [0.3000, 0.4000]]))

In [382]:
torch.div(first_tensor, second_tensor)

tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

In [383]:
# Matrix Multiplication
first_tensor @ second_tensor, torch.matmul(first_tensor, second_tensor)

(tensor([[19, 22],
         [43, 50]]),
 tensor([[19, 22],
         [43, 50]]))

In [384]:
# Can only multiply matrices that the number of columns in the first matrix must equal the number of rows in the second matrix
torch.rand(3, 2) @ torch.rand(2, 3)

tensor([[0.0916, 0.3444, 0.4103],
        [0.2712, 1.0283, 1.1994],
        [0.2038, 0.8696, 0.7183]])

In [385]:
torch.rand(3, 2) @ torch.rand(3, 2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [386]:
# To multiply tensors, if one tensor has a shape like (3, 3, 2), the other tensor must also have the same number of matrices in the first dimension. In this case, both tensors should have a shape of (3, X, Y) where X and Y can be different, but X must match the second-to-last dimension of the first tensor.
torch.rand(3, 3, 2) @ torch.rand(3, 2, 3)

tensor([[[0.2368, 0.1804, 0.5335],
         [0.5269, 0.8174, 1.3786],
         [0.1903, 0.4464, 0.5676]],

        [[0.4530, 0.1870, 0.0621],
         [1.2041, 0.7204, 0.1374],
         [0.0744, 0.0634, 0.0061]],

        [[0.2102, 0.2696, 0.3354],
         [0.0870, 0.1813, 0.2964],
         [0.3404, 0.2872, 0.2053]]])

In [387]:
torch.rand(3, 3, 2) @ torch.rand(4, 2, 3)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [388]:
# Fix shape error
# Switch axes or dimensions of tensor (transpose)
tensor_A = torch.tensor([[1, 2], 
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[5, 6], 
                         [7, 8], 
                         [9, 10]])

tensor_A, tensor_A.T

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[1, 3, 5],
         [2, 4, 6]]))

In [389]:
tensor_A.shape, tensor_A.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [390]:
# Change tensor_A shape "tensor_A.T"
torch.matmul(tensor_A.T, tensor_B), 

(tensor([[ 71,  80],
         [ 92, 104]]),)

In [391]:
# Didn't change tensor_A shape and got error
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)